### PR TITLE
fix: escape single quotes in response body

### LINKED ISSUE #12: problematic single quotes
I came across another thing. Something like this: a single single-quote

```json
{
  "contents": "'\n"
}
```

throws `zsh:1: unmatched "`

When there is an equal number of single quotes they just get removed in the result window. Doesn't seem to happen with double quotes or backticks.

### PR DESCRIPTION
**Pull request by NTBBloodbath**
This PR should fix the escaping of the single quotes in the response body. Should close #12

@rudotriton could you please test it to see if everything is alright? I didn't tested it, but should be working well.

### CODE REVIEW

File: lua/rest-nvim/init.lua [hunk 1]
```diff
@@ -260,7 +260,7 @@ local function curl_cmd(opts)
 		if json_body then
 			-- Format JSON output and then add it into the buffer
 			-- line by line because Vim doesn't allow strings with newlines
-			local out = fn.system("echo -E '" .. line .. "' | jq .")
+			local out = fn.system("echo -E '" .. string.gsub(line, "[']", "\\%1") .. "' | jq .")
```
Comment (disrupted) [inline lua/rest-nvim/init.lua:263]: Instead of piping into stdin using echo I believe we could make use of the second argument to the system method
```suggestion
			local out = fn.system("jq", line)
```

**Review by disrupted — CHANGES_REQUESTED** [review]

File: lua/rest-nvim/init.lua (hunk 1 above)
Comment (disrupted) [reply lua/rest-nvim/init.lua:263]: https://neovim.io/doc/user/eval.html#system()

Comment (rudotriton) [reply lua/rest-nvim/init.lua:263]: well that is cool and it clears both of my recent issues

FWIW, `"\\%1"` wouldn't fix it anyway, but `"'\\%1'"` would

Comment (NTBBloodbath) [reply lua/rest-nvim/init.lua]: Thank you for the suggestion, it makes sense! :)
